.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. filbit_qt test_filbit_qt
clean: FORCE
	$(MAKE) -C .. filbit_qt_clean test_filbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_filbit_qt_check
filbit-qt filbit-qt.exe: FORCE
	 $(MAKE) -C .. filbit_qt
